import { writable } from 'svelte/store';
import type { ConversionState, ConversionResult, IssuesExportResult, Tab } from '$lib/types';

export const DEFAULT_SKIP_PATTERNS = [
  'node_modules/',
  '.git/',
  '*.min.js',
  '*.min.css',
  '*.map',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'composer.lock',
  'Gemfile.lock',
  'Pipfile.lock',
  'poetry.lock',
  'Cargo.lock',
  'go.sum',
  'mix.lock',
  'pubspec.lock',
  '*.test.js',
  '*.spec.js',
  '*.test.ts',
  '*.spec.ts',
  '__tests__/',
  'test/',
  'tests/',
  '.gitignore',
  '.gitattributes',
  '.editorconfig',
  '.prettierrc*',
  '.eslintrc*',
  '*.config.js',
  '*.config.ts',
  '*.config.json',
  '.env*',
  '.env.local',
  '.env.production',
  '.env.development',
  '.env.test',
  '.envrc',
  '.nvmrc',
  '.node-version',
  '.ruby-version',
  '.python-version',
  '.tool-versions',
  'tsconfig.json',
  'babel.config.js',
  'webpack.config.js',
  'vite.config.js',
  'jest.config.js',
  '*.md',
  '*.bundle.js',
  '*.chunk.js',
  '*.pyc',
  '*.pyo',
  '__pycache__/',
  '*.egg-info/',
  '*.whl',
  '.tox/',
  'venv/',
  'env/',
  '.pytest_cache/',
  '*.class',
  '*.jar',
  '*.war',
  '*.o',
  '*.obj',
  '*.exe',
  '*.dll',
  '*.so',
  '*.a',
  '*.lib',
  '*.pdb',
  '*.idb',
  '*.dSYM/',
  'core',
  'core.*',
  '.DS_Store',
  'Thumbs.db',
  'desktop.ini',
  '.directory',
  '*.log',
  '*.tmp',
  '*.temp',
  '*.webp',
  '*.png',
  '*.jpg',
  '*.jpeg',
  '*.gif',
  '*.svg',
  '*.ico',
  '*.bmp',
  '*.tiff',
  '*.tif',
  '*.raw',
  '*.psd',
  '*.ai',
  '*.sketch',
  '*.fig',
  '*.xd',
  '*.eps',
  '*.indd',
  '*.pdf',
  '*.doc',
  '*.docx',
  '*.xls',
  '*.xlsx',
  '*.ppt',
  '*.pptx',
  '*.zip',
  '*.rar',
  '*.7z',
  '*.tar',
  '*.gz',
  '*.bin',
  '*.dat',
  '*.db',
  '*.sqlite',
  '*.sqlite3',
  '*.db3',
  '*.s3db',
  '*.mdb',
  '*.accdb',
  '*.dbf',
  '*.mp3',
  '*.mp4',
  '*.avi',
  '*.mov',
  '*.wav',
  '*.flac',
  '*.ttf',
  '*.otf',
  '*.woff',
  '*.woff2',
  '*.eot',
  '*.swp',
  '*.swo',
  '*~',
  '*.bak',
  '*.backup',
  '*.old',
  '*.orig',
  'logs/',
  'tmp/',
  '.gradle/',
  '.maven/',
  '.cargo/',
  '.nuget/',
  'cmake-build-*/',
  '.next/',
  '.nuxt/',
  '.svelte-kit/',
  '.turbo/',
  'coverage/',
  '.nyc_output/',
  '.cache/',
  '.fleet/',
  '.sublime-*',
  '.history/',
  'LICENSE',
  'LICENSE.txt',
  'LICENSE.md',
  'dist/',
  'build/',
  'out/',
  'target/',
  'bin/',
  '.vscode/',
  '.idea/',
].join('\n');

const initialState: ConversionState = {
  tab: 'code',
  status: 'idle',
  tokenStatus: 'idle',
  progress: { current: 0, total: 0 },
  tokenProgress: 0,
  message: '',
  error: null,
  result: null,
  issuesResult: null,
  repoUrl: '',
  skipLargeFiles: true,
  removeLicenseHeaders: true,
  // Стартовое значение — список по умолчанию, но пользовательский ввод заменяет целиком
  skipPatterns: DEFAULT_SKIP_PATTERNS,
  includeOpenIssues: true,
  includeClosedIssues: true,
};

export const conversionStore = writable<ConversionState>(initialState);

export function resetState(tab?: Tab) {
  conversionStore.update((s) => ({
    ...initialState,
    tab: tab ?? s.tab,
    repoUrl: s.repoUrl,
  }));
}

export function setTab(tab: Tab) {
  conversionStore.update((s) => ({ ...s, tab }));
}

export function setRepoUrl(url: string) {
  conversionStore.update((s) => ({ ...s, repoUrl: url }));
}

export function setOptions(updates: Partial<ConversionState>) {
  conversionStore.update((s) => ({
    ...s,
    ...updates,
    // если передан skipPatterns (включая пустую строку), заменить полностью
    ...(updates.skipPatterns !== undefined ? { skipPatterns: updates.skipPatterns } : {}),
  }));
}

export function setResult(result: ConversionResult) {
  conversionStore.update((s) => ({
    ...s,
    result,
    issuesResult: null,
  }));
}

export function setIssuesResult(result: IssuesExportResult) {
  conversionStore.update((s) => ({
    ...s,
    issuesResult: result,
    result: null,
  }));
}
